import asyncio, re
from playwright.async_api import async_playwright
R=[]
def ok(n,c,x=''): R.append(f"{'PASS' if c else 'FAIL'}  {n}{'  ['+str(x)+']' if x!='' else ''}")
async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch(); ctx = await b.new_context(viewport={'width':390,'height':844}, accept_downloads=True); await ctx.add_init_script("try{localStorage.setItem('profitaxi.paidMode','1')}catch(e){}")
        pg = await ctx.new_page(); errs=[]
        pg.on('pageerror', lambda e: errs.append(str(e)))
        pg.on('console', lambda m: errs.append(m.text) if m.type=='error' and 'TUNNEL' not in m.text and 'fonts' not in m.text else None)
        base='http://localhost:8765'
        await pg.goto(base+'/app'); await pg.evaluate('localStorage.clear()'); await pg.goto(base+'/app#/register'); await pg.wait_for_timeout(400)
        T = lambda s: pg.locator(s)
        # --- Регистрация: валидации ---
        await pg.fill('input[autocomplete=name]','Тест Шофьор'); await pg.fill('input[type=email]','test@test.bg'); await pg.fill('input[type=password]','123456')
        await pg.fill('input[type=tel]','0877111222'); await pg.wait_for_timeout(100)
        await pg.click('button[type=submit]'); await pg.wait_for_timeout(200)
        ok('Регистрация без град дава грешка', 'град' in (await T('.err').inner_text()).lower() or 'кола' in (await T('.err').inner_text()).lower(), await T('.err').inner_text())
        await pg.select_option('select >> nth=0','Пловдив'); await pg.wait_for_timeout(150)
        opts = await pg.eval_on_selector('select >> nth=1', 'e=>[...e.options].map(o=>o.textContent)')
        ok('Пловдив показва 5-те фирми + Друга', 'ONE Такси – 032 22 22' in opts and 'Елма Такси' in opts and any('Друга' in o for o in opts), len(opts))
        await pg.select_option('select >> nth=0','Хасково'); await pg.wait_for_timeout(150)
        opts = await pg.eval_on_selector('select >> nth=1', 'e=>[...e.options].map(o=>o.textContent)')
        ok('Друг голям град (Хасково) има само „Друга“', len(opts)==2 and 'Друга' in opts[1], opts)
        await pg.select_option('select >> nth=1', index=1); await pg.wait_for_timeout(150)
        ok('„Друга“ показва поле за име на фирмата', await T('input[placeholder="Име на фирмата"]').count()==1)
        await pg.click('text=Под наем'); await pg.click('input[type=checkbox]')
        await pg.click('button[type=submit]'); await pg.wait_for_timeout(200)
        ok('„Друга“ без име дава грешка', 'фирма' in (await T('.err').inner_text()).lower(), await T('.err').inner_text())
        await pg.fill('input[placeholder="Име на фирмата"]','Хасково Такси Експрес')
        await pg.click('button[type=submit]'); await pg.wait_for_timeout(500)
        ok('Успешна регистрация → презентацията', '#/guide' in pg.url and await T('.guide-page').count()==16, pg.url)
        ok('Презентация: бутон за PDF', await T('a[download="Chisto-vavedenie.pdf"]').count()>=1)
        await pg.click('.guide-next .btn'); await pg.wait_for_timeout(400)
        ok('„Нататък“ → първа настройка', '#/onboarding' in pg.url, pg.url)
        # --- Първа настройка ---
        await pg.click('.tile'); await pg.keyboard.type('140'); await pg.click('text=Готово')
        await pg.click('text=Напред'); await pg.click('text=Дизел'); await pg.click('text=Напред')
        await pg.click('.seg-btn:has-text("На ден")'); await pg.click('.tile'); await pg.keyboard.type('10'); await pg.click('text=Готово')
        await pg.click('text=Напред'); await pg.click('text=Започни'); await pg.wait_for_timeout(500)
        ok('След настройката → начален екран', '#/home' in pg.url)
        # --- Разходка след регистрация ---
        await pg.wait_for_timeout(700)
        ok('Разходка при първото влизане', await T('.tour').count()==1)
        await pg.click('.tour-btns .btn-primary'); await pg.wait_for_timeout(250)
        ok('Разходка: Напред показва стъпка 2', '2 от' in await T('.tour-step').inner_text())
        await pg.click('.tour-btns .btn-ghost'); await pg.wait_for_timeout(250)
        ok('Разходка: Назад връща на стъпка 1', '1 от' in await T('.tour-step').inner_text())
        await pg.click('.tour-skip'); await pg.wait_for_timeout(300)
        await pg.goto(base+'/app#/stats'); await pg.goto(base+'/app#/home'); await pg.wait_for_timeout(900)
        ok('След „Пропусни“ не се показва пак', await T('.tour').count()==0)
        await pg.goto(base+'/app#/costs'); await pg.wait_for_timeout(400)
        body = await T('#app').inner_text()
        ok('Наем 140 €/седм. и ефир 10 €/ден са в постоянните разходи', 'Наем на колата' in body and 'Ефир / диспечер' in body)
        ok('Под наем няма винетка/застраховка', 'Винетка' not in body and 'Гражданска' not in body)
        await pg.click('.hero-btn'); await pg.wait_for_timeout(300)
        chips = await T('.sheet .chip-btn').all_inner_texts()
        ok('Под наем не може да се добави винетка/застраховка', not any(x in chips for x in ['Винетка','Гражданска отговорност','Каско','Технически преглед']), chips)
        await pg.keyboard.press('Escape'); await pg.wait_for_timeout(300)
        await pg.goto(base+'/app#/home'); await pg.wait_for_timeout(300)
        ok('Първия ден вместо нули има „Добре дошъл“ с 3 стъпки', await T('.first-day').count()==1 and await T('.meter').count()==0)
        # --- Смяна ---
        await pg.click('.shift-cta'); await pg.keyboard.type('250000'); await pg.click('text=Старт'); await pg.wait_for_timeout(500)
        ok('Активна смяна с таймер', await T('[data-timer]').count()==1)
        await pg.click('.drive-top .chip'); await pg.wait_for_timeout(300)
        ok('Празна смяна: без червен минус, а „Въведи кеш и карта“', 'Въведи кеш и карта' in await T('.save-bar').inner_text())
        await pg.click('[data-sec=inc] .f-row >> nth=0'); await pg.keyboard.type('100'); await pg.click('.np-actions >> text=Запиши'); await pg.wait_for_timeout(150)
        await pg.click('[data-sec=inc] .f-row >> nth=0'); await pg.keyboard.type('20,5'); await pg.click('.np-actions >> text=Добави към'); await pg.wait_for_timeout(150)
        cash = await T('[data-sec=inc] .f-row >> nth=0').inner_text()
        ok('Кеш: 100 + добави 20,50 = 120,50 €', '120,50' in cash, cash.replace('\n',' '))
        await pg.click('[data-sec=inc] .f-row >> nth=1'); await pg.keyboard.type('30'); await pg.click('.np-actions >> text=Запиши')
        await pg.click('[data-sec=exp] .f-row >> nth=0'); await pg.keyboard.type('40'); await pg.click('.np-field >> nth=1'); await pg.keyboard.type('28,5'); await pg.click('.np-actions >> text=Добави'); await pg.wait_for_timeout(150)
        exp = await T('.exp-list').inner_text()
        ok('Гориво 40 € / 28,5 л с цена на литър', '40 €' in exp and '28,5' in exp, exp.replace('\n',' '))
        quick = await T('[data-sec=exp] .f-list').inner_text()
        ok('Разходите са 3 реда + „Друг разход“', await T('[data-sec=exp] .f-row').count()==4 and 'Друг разход' in quick and 'Гориво' in quick, quick.replace('\n',' '))
        await pg.click('[data-sec=exp] .f-row >> nth=3'); await pg.wait_for_timeout(250)
        other = await T('.sheet').inner_text()
        ok('Няма „Храна“, има „Глоба“ в „Друг разход“', 'Храна' not in other and 'Глоба' in other)
        await pg.keyboard.press('Escape'); await pg.wait_for_timeout(300)
        ok('Приходи, Разходи и Данни са три полета едно под друго', await T('.f-card').count()==3 and await T('[data-sec=data] .f-row').count()>=5)
        net = await T('.save-bar .sum b').inner_text()
        ok('Чисто за смяната = 150,5 − 40 − постоянни (20 + 10)', net.replace('−','-').strip() in ('81 €','80 €'), net)
        await pg.click('.save-bar .btn'); await pg.wait_for_timeout(400)
        ok('„Запази“ при активна смяна я оставя активна', await T('[data-timer]').count()==1)
        await pg.click('text=Приключи смяната'); await pg.wait_for_timeout(300)
        ok('„Приключи смяната“ пита само за крайния км (сумите не се въвеждат пак)', await T('.sheet .np-field').count()==1 and 'Краен км' in await T('.sheet').inner_text())
        await pg.keyboard.type('250210'); await pg.click('.np-actions >> text=Приключи'); await pg.wait_for_timeout(500)
        ok('„Приключи“ връща към началото без активна смяна', '#/home' in pg.url and await T('[data-timer]').count()==0)
        await pg.wait_for_timeout(300)
        ok('След „Приключи“ излиза картата с резултата', await T('.result-net').count()==1 and '€' in await T('.result-net').inner_text(), await T('.result-net').inner_text() if await T('.result-net').count() else '')
        await pg.click('.result >> text=Супер'); await pg.wait_for_timeout(400)
        # --- Смени и редакция ---
        await pg.goto(base+'/app#/shifts'); await pg.wait_for_timeout(300)
        rows = await T('.shift-row').count()
        ok('Смяната е в списъка', rows==1, rows)
        await pg.click('.shift-row'); await pg.wait_for_timeout(300)
        await pg.click('text=Като предишната'); await pg.wait_for_timeout(200)
        ok('„Като предишната“ без друга смяна дава съобщение', 'Няма предишна' in await T('#toast').inner_text())
        await pg.click('.icon-btn[aria-label="Изтрий смяната"]'); await pg.click('.sheet >> text=Изтрий'); await pg.wait_for_timeout(500)
        ok('Изтриване на смяна', await T('.shift-row').count()==0)
        # --- Минала смяна + копиране на разходи ---
        await pg.goto(base+'/app#/shift/new'); await pg.wait_for_timeout(300)
        await pg.click('[data-sec=inc] .f-row >> nth=0'); await pg.keyboard.type('120'); await pg.click('.np-actions >> text=Запиши')
        await pg.click('[data-sec=exp] .f-row >> nth=1'); await pg.keyboard.type('6'); await pg.click('.np-actions >> text=Добави')
        await pg.click('.save-bar .btn'); await pg.wait_for_timeout(400)
        if await T('.result').count(): await pg.click('.result >> text=Супер'); await pg.wait_for_timeout(400)
        await pg.goto(base+'/app#/shift/new'); await pg.wait_for_timeout(300)
        await pg.click('text=Като предишната'); await pg.wait_for_timeout(200)
        ok('Копиране на разходите от предишната смяна', 'Автомивка' in await T('.exp-list').inner_text())
        await pg.click('.back'); await pg.wait_for_timeout(300)
        # --- Невалидни данни ---
        await pg.goto(base+'/app#/shift/new'); await pg.wait_for_timeout(300)
        await pg.click('[data-sec=data] .f-row >> nth=0'); await pg.keyboard.type('1000'); await pg.click('.np-actions >> text=Запиши'); await pg.wait_for_timeout(100)
        await pg.click('[data-sec=data] .f-row >> nth=1'); await pg.keyboard.type('5'); await pg.click('.np-actions >> text=Запиши'); await pg.wait_for_timeout(100)
        await pg.click('.save-bar .btn'); await pg.wait_for_timeout(200)
        ok('Краен км < начален не се записва', 'километража' in await T('#toast').inner_text())
        await pg.click('.back'); await pg.wait_for_timeout(300)
        # --- Постоянен разход + Платено ---
        await pg.goto(base+'/app#/costs'); await pg.wait_for_timeout(300)
        await pg.click('.hero-btn'); await pg.wait_for_timeout(300)
        await pg.click('.sheet .chip-btn:has-text("Разрешително")')
        await pg.fill('.sheet input[inputmode=decimal]','100')
        await pg.evaluate("(()=>{const d=new Date();d.setDate(d.getDate()+2);const i=document.querySelector('.sheet input[type=date]');i.value=d.toISOString().slice(0,10);i.dispatchEvent(new Event('input',{bubbles:true}));i.dispatchEvent(new Event('change',{bubbles:true}))})()")
        await pg.click('.sheet >> text=Запази'); await pg.wait_for_timeout(500)
        body = await T('#app').inner_text()
        ok('Нов разход с падеж след 2 дни е в „Предстоящи плащания“', 'Разрешително' in body)
        await pg.click('.rem-actions .btn >> nth=0'); await pg.wait_for_timeout(500)
        ok('„Платено“ мести падежа с година', 'Следващо плащане' in await T('#toast').inner_text(), await T('#toast').inner_text())
        # --- Напомняне по км ---
        await pg.click('text=Напомняне'); await pg.wait_for_timeout(300)
        await pg.fill('.sheet input[placeholder="напр. Смяна на масло"]','Масло')
        await pg.fill('.sheet input[inputmode=numeric] >> nth=0','250500')
        await pg.click('.sheet >> text=Запази'); await pg.wait_for_timeout(400)
        ok('Напомняне по км е добавено', 'Масло' in await T('#app').inner_text())
        # --- Статистика + Excel ---
        await pg.goto(base+'/app#/stats'); await pg.wait_for_timeout(500)
        async with pg.expect_download() as dl:
            await pg.click('.hero-btn[aria-label="Свали в Excel"]')
        d = await dl.value; path = await d.path(); txt = open(path, encoding='utf-8-sig').read()
        ok('Excel файлът се сваля и съдържа смените', 'Дата;Начало' in txt and 'Чиста печалба' in txt, d.suggested_filename)
        for u in ['day','week','year','custom']:
            await pg.click(f'.seg-btn >> nth={["day","week","month","year","custom"].index(u)}'); await pg.wait_for_timeout(250)
        ok('Всички периоди в статистиката се отварят без грешка', not errs, errs[:2])
        # --- Профил ---
        await pg.goto(base+'/app#/car'); await pg.wait_for_timeout(300)
        ctxt = await T('#app').inner_text()
        ok('„Настройки на колата“ е отделна страница с вид кола, гориво и ефир', all(x in ctxt for x in ['Колата е','Гориво','Ефир / диспечер']))
        await pg.click('.seg-btn:has-text("Седмица")'); await pg.click('.tile:has-text("Такса")'); await pg.keyboard.type('40'); await pg.click('text=Готово')
        await pg.click('.save-bar .btn'); await pg.wait_for_timeout(400)
        ok('При смяна на ефира пита от кога важи', 'От кога важи' in await T('.sheet').inner_text())
        await pg.click('.sheet .btn-primary'); await pg.wait_for_timeout(500)
        await pg.goto(base+'/app#/costs'); await pg.wait_for_timeout(300)
        ok('Смяна на ефира на 40 €/седм. от профила', '40 € на седмица' in await T('#app').inner_text())
        await pg.goto(base+'/app#/profile'); await pg.wait_for_timeout(300)
        txt = await T('#app').inner_text()
        ok('„Лични данни“ е само личното: данни, снимки, изглед, парола, изход', all(x.lower() in txt.lower() for x in ['Лични данни','Снимки','Изглед','Смяна на паролата','Поверителност','Общи условия','Изход']) and not any(x.lower() in txt.lower() for x in ['Ефир / диспечер','Отчет в PDF','Всички смени (Excel)','Пиши ни']))
        await pg.click('.seg-btn:has-text("Тъмна")'); await pg.wait_for_timeout(150)
        ok('Тъмна тема се включва', await pg.evaluate('document.documentElement.dataset.theme')=='dark')
        await pg.click('.seg-btn:has-text("Светла")'); await pg.wait_for_timeout(150)
        ok('Изгледът е само Като телефона / Светла / Тъмна', await pg.evaluate('document.documentElement.dataset.theme')=='light' and await pg.locator('.seg-btn:has-text("За слънце")').count()==0)
        await pg.click('.seg-btn:has-text("Голям")'); await pg.wait_for_timeout(150)
        ok('Размер на текста „Голям“ уголемява всичко', await pg.evaluate('document.documentElement.style.fontSize')=='112.5%')
        await pg.click('.seg-btn:has-text("Нормален")')
        await pg.click('.seg-btn:has-text("Като телефона")')
        await pg.click('text=Смяна на паролата'); await pg.wait_for_timeout(250)
        await pg.fill('.sheet input >> nth=0','грешна'); await pg.fill('.sheet input >> nth=1','654321'); await pg.click('.sheet .btn-page'); await pg.wait_for_timeout(150)
        ok('Грешна текуща парола се отказва', 'Грешна' in await T('.sheet .err').inner_text())
        await pg.fill('.sheet input >> nth=0','123456'); await pg.click('.sheet .btn-page'); await pg.wait_for_timeout(400)
        await pg.click('text=Изход'); await pg.wait_for_timeout(300)
        await pg.fill('input[type=email]','test@test.bg'); await pg.fill('input[type=password]','123456'); await pg.click('button[type=submit]'); await pg.wait_for_timeout(300)
        ok('Старата парола вече не работи', 'Грешен' in await T('.err').inner_text())
        await pg.fill('input[type=password]','654321'); await pg.click('button[type=submit]'); await pg.wait_for_timeout(400)
        ok('Вход с новата парола', '#/home' in pg.url)
        # --- Ширина и грешки ---
        for route in ['home','shifts','stats','costs','profile','car','me','money','shift/new']:
            await pg.goto(base+'/app#/'+route); await pg.wait_for_timeout(350)
            w = await pg.evaluate('document.documentElement.scrollWidth')
            if w>390: ok(f'Без хоризонтално превъртане: {route}', False, w)
        ok('Без хоризонтално превъртане на всички страници (390 px)', not any('превъртане' in r and r.startswith('FAIL') for r in R))
        ok('Без грешки в конзолата', not errs, errs[:3])
        print('\n'.join(R)); print('FAILS:', sum(r.startswith('FAIL') for r in R), '/', len(R))
        await b.close()
try:
    asyncio.run(main())
except Exception as e:
    print('\n'.join(R)); print('CRASH:', str(e).split('\n')[0])
