import asyncio, re
from playwright.async_api import async_playwright
R=[]
def ok(n,c,x=''): R.append(f"{'PASS' if c else 'FAIL'}  {n}{'  ['+str(x)+']' if x!='' else ''}")
async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch(); ctx = await b.new_context(viewport={'width':390,'height':844}, accept_downloads=True)
        pg = await ctx.new_page(); errs=[]
        pg.on('pageerror', lambda e: errs.append(str(e)))
        pg.on('console', lambda m: errs.append(m.text) if m.type=='error' and 'TUNNEL' not in m.text and 'fonts' not in m.text else None)
        base='http://localhost:8765'
        await pg.goto(base+'/app'); await pg.evaluate('localStorage.clear()'); await pg.goto(base+'/app#/register'); await pg.wait_for_timeout(400)
        T = lambda s: pg.locator(s)
        # --- Регистрация: валидации ---
        await pg.fill('input[autocomplete=name]','Тест Шофьор'); await pg.fill('input[type=email]','test@test.bg'); await pg.fill('input[type=password]','123456')
        await pg.fill('input[type=tel]','0877111222'); await pg.click('text=Изпрати код по SMS'); await pg.wait_for_timeout(250); _c = re.findall(r'\d{4}', await pg.inner_text('#toast'))[-1]; await pg.fill('input[placeholder="4 цифри"]', _c); await pg.click('.sms-row >> text=Потвърди'); await pg.wait_for_timeout(150)
        await pg.click('button[type=submit]'); await pg.wait_for_timeout(200)
        ok('Регистрация без град дава грешка', 'град' in (await T('.err').inner_text()).lower() or 'кола' in (await T('.err').inner_text()).lower(), await T('.err').inner_text())
        await pg.select_option('select >> nth=0','Пловдив'); await pg.wait_for_timeout(150)
        opts = await pg.eval_on_selector('select >> nth=1', 'e=>[...e.options].map(o=>o.textContent)')
        ok('Пловдив показва 5-те фирми + Друга', 'ONE Такси – 032 22 22' in opts and 'Елма Такси' in opts and any('Друга' in o for o in opts), len(opts))
        await pg.select_option('select >> nth=0','Хасково'); await pg.wait_for_timeout(150)
        opts = await pg.eval_on_selector('select >> nth=1', 'e=>[...e.options].map(o=>o.textContent)')
        ok('Друг голям град (Хасково) има само „Друга“', len(opts)==2 and 'Друга' in opts[1], opts)
        await pg.select_option('select >> nth=1', index=1); await pg.wait_for_timeout(150)
        ok('„Друга“ показва поле за име на фирмата', await T('input[placeholder="Име на фирмата"]').count()==1)
        await pg.click('text=Под наем'); await pg.click('input[type=checkbox]')
        await pg.click('button[type=submit]'); await pg.wait_for_timeout(200)
        ok('„Друга“ без име дава грешка', 'фирма' in (await T('.err').inner_text()).lower(), await T('.err').inner_text())
        await pg.fill('input[placeholder="Име на фирмата"]','Хасково Такси Експрес')
        await pg.click('button[type=submit]'); await pg.wait_for_timeout(500)
        ok('Успешна регистрация → първа настройка', '#/onboarding' in pg.url, pg.url)
        # --- Първа настройка ---
        await pg.click('.tile'); await pg.keyboard.type('140'); await pg.click('text=Готово')
        await pg.click('text=Напред'); await pg.click('text=Дизел'); await pg.click('text=Напред')
        await pg.click('.seg-btn:has-text("На ден")'); await pg.click('.tile'); await pg.keyboard.type('10'); await pg.click('text=Готово')
        await pg.click('text=Напред'); await pg.click('text=Започни'); await pg.wait_for_timeout(500)
        ok('След настройката → начален екран', '#/home' in pg.url)
        # --- Разходка след регистрация ---
        await pg.wait_for_timeout(700)
        ok('Разходка при първото влизане', await T('.tour').count()==1)
        await pg.click('.tour-btns .btn-primary'); await pg.wait_for_timeout(250)
        ok('Разходка: Напред показва стъпка 2', '2 от' in await T('.tour-step').inner_text())
        await pg.click('.tour-btns .btn-ghost'); await pg.wait_for_timeout(250)
        ok('Разходка: Назад връща на стъпка 1', '1 от' in await T('.tour-step').inner_text())
        await pg.click('.tour-skip'); await pg.wait_for_timeout(300)
        await pg.goto(base+'/app#/stats'); await pg.goto(base+'/app#/home'); await pg.wait_for_timeout(900)
        ok('След „Пропусни“ не се показва пак', await T('.tour').count()==0)
        await pg.goto(base+'/app#/costs'); await pg.wait_for_timeout(400)
        body = await T('#app').inner_text()
        ok('Наем 140 €/седм. и ефир 10 €/ден са в постоянните разходи', 'Наем на колата' in body and 'Ефир / диспечер' in body)
        ok('Под наем няма винетка/застраховка', 'Винетка' not in body and 'Гражданска' not in body)
        await pg.click('.hero-btn'); await pg.wait_for_timeout(300)
        chips = await T('.sheet .chip-btn').all_inner_texts()
        ok('Под наем не може да се добави винетка/застраховка', not any(x in chips for x in ['Винетка','Гражданска отговорност','Каско','Технически преглед']), chips)
        await pg.keyboard.press('Escape'); await pg.wait_for_timeout(300)
        await pg.goto(base+'/app#/home'); await pg.wait_for_timeout(300)
        ok('Първия ден вместо нули има „Добре дошъл“ с 3 стъпки', await T('.first-day').count()==1 and await T('.meter').count()==0)
        # --- Смяна ---
        await pg.click('.shift-cta'); await pg.keyboard.type('250000'); await pg.click('text=Старт'); await pg.wait_for_timeout(500)
        ok('Активна смяна с таймер', await T('[data-timer]').count()==1)
        await pg.click('text=Отчет'); await pg.wait_for_timeout(300)
        ok('Празна смяна: без червен минус, а „Въведи кеш и карта“', 'Въведи кеш и карта' in await T('.save-bar').inner_text())
        await pg.click('.tile >> nth=0'); await pg.keyboard.type('100'); await pg.click('.np-actions >> text=Запиши'); await pg.wait_for_timeout(150)
        await pg.click('.tile >> nth=0'); await pg.keyboard.type('20,5'); await pg.click('.np-actions >> text=+ Добави'); await pg.wait_for_timeout(150)
        cash = await T('.tile >> nth=0').inner_text()
        ok('Кеш: 100 + добави 20,50 = 120,50 €', '120,50' in cash, cash.replace('\n',' '))
        await pg.click('.tile >> nth=1'); await pg.keyboard.type('30'); await pg.click('.np-actions >> text=Запиши')
        await pg.click('.quick button >> nth=0'); await pg.keyboard.type('40'); await pg.click('.np-field >> nth=1'); await pg.keyboard.type('28,5'); await pg.click('.np-actions >> text=Добави'); await pg.wait_for_timeout(150)
        exp = await T('.exp-list').inner_text()
        ok('Гориво 40 € / 28,5 л с цена на литър', '40 €' in exp and '28,5' in exp, exp.replace('\n',' '))
        quick = await T('.quick').inner_text()
        ok('Бързите разходи са 3 + „Друг разход“', quick.count('\n')>=3 and 'Друг разход' in quick and 'Гориво' in quick, quick.replace('\n',' '))
        await pg.click('.quick-more'); await pg.wait_for_timeout(250)
        other = await T('.sheet').inner_text()
        ok('Няма „Храна“, има „Глоба“ в „Друг разход“', 'Храна' not in other and 'Глоба' in other)
        await pg.keyboard.press('Escape'); await pg.wait_for_timeout(300)
        ok('Км/време/бележка са скрити под „Още“', not await T('.km-row').is_visible())
        net = await T('.save-bar .sum b').inner_text()
        ok('Чисто за смяната = 150,5 − 40 − постоянни (20 + 10)', net.replace('−','-').strip() in ('81 €','80 €'), net)
        await pg.click('.save-bar .btn'); await pg.wait_for_timeout(400)
        ok('„Запази“ при активна смяна я оставя активна', await T('[data-timer]').count()==1)
        await pg.click('text=Приключих'); await pg.wait_for_timeout(300)
        await pg.click('.km-row .tile >> nth=1'); await pg.keyboard.type('250210'); await pg.click('.np-actions >> text=Запиши'); await pg.wait_for_timeout(150)
        await pg.click('.save-bar .btn'); await pg.wait_for_timeout(500)
        ok('„Приключи“ връща към началото без активна смяна', '#/home' in pg.url and await T('[data-timer]').count()==0)
        await pg.wait_for_timeout(300)
        ok('След „Приключи“ излиза картата с резултата', await T('.result-net').count()==1 and '€' in await T('.result-net').inner_text(), await T('.result-net').inner_text() if await T('.result-net').count() else '')
        await pg.click('.result >> text=Супер'); await pg.wait_for_timeout(400)
        # --- Смени и редакция ---
        await pg.goto(base+'/app#/shifts'); await pg.wait_for_timeout(300)
        rows = await T('.shift-row').count()
        ok('Смяната е в списъка', rows==1, rows)
        await pg.click('.shift-row'); await pg.wait_for_timeout(300)
        await pg.click('details.more summary'); await pg.wait_for_timeout(150)
        await pg.click('text=Разходите от предишната смяна'); await pg.wait_for_timeout(200)
        ok('„Разходите от предишната смяна“ без друга смяна дава съобщение', 'Няма предишна' in await T('#toast').inner_text())
        await pg.click('.icon-btn[aria-label="Изтрий смяната"]'); await pg.click('.sheet >> text=Изтрий'); await pg.wait_for_timeout(500)
        ok('Изтриване на смяна', await T('.shift-row').count()==0)
        # --- Минала смяна + копиране на разходи ---
        await pg.goto(base+'/app#/shift/new'); await pg.wait_for_timeout(300)
        await pg.click('.tile >> nth=0'); await pg.keyboard.type('120'); await pg.click('.np-actions >> text=Запиши')
        await pg.click('.quick button >> nth=1'); await pg.keyboard.type('6'); await pg.click('.np-actions >> text=Добави')
        await pg.click('.save-bar .btn'); await pg.wait_for_timeout(400)
        if await T('.result').count(): await pg.click('.result >> text=Супер'); await pg.wait_for_timeout(400)
        await pg.goto(base+'/app#/shift/new'); await pg.wait_for_timeout(300)
        await pg.click('details.more summary'); await pg.wait_for_timeout(150)
        await pg.click('text=Разходите от предишната смяна'); await pg.wait_for_timeout(200)
        ok('Копиране на разходите от предишната смяна', 'Автомивка' in await T('.exp-list').inner_text())
        await pg.click('.back'); await pg.wait_for_timeout(300)
        # --- Невалидни данни ---
        await pg.goto(base+'/app#/shift/new'); await pg.wait_for_timeout(300)
        await pg.click('details.more summary'); await pg.wait_for_timeout(150)
        await pg.click('.km-row .tile >> nth=0'); await pg.keyboard.type('1000'); await pg.click('.np-actions >> text=Запиши'); await pg.wait_for_timeout(100)
        await pg.click('.km-row .tile >> nth=1'); await pg.keyboard.type('5'); await pg.click('.np-actions >> text=Запиши'); await pg.wait_for_timeout(100)
        await pg.click('.save-bar .btn'); await pg.wait_for_timeout(200)
        ok('Краен км < начален не се записва', 'километража' in await T('#toast').inner_text())
        await pg.click('.back'); await pg.wait_for_timeout(300)
        # --- Постоянен разход + Платено ---
        await pg.goto(base+'/app#/costs'); await pg.wait_for_timeout(300)
        await pg.click('.hero-btn'); await pg.wait_for_timeout(300)
        await pg.click('.sheet .chip-btn:has-text("Разрешително")')
        await pg.fill('.sheet input[inputmode=decimal]','100')
        await pg.fill('.sheet input[type=date] >> nth=0', (await pg.evaluate("(()=>{const d=new Date();d.setDate(d.getDate()+2);return d.toISOString().slice(0,10)})()")))
        await pg.click('.sheet >> text=Запази'); await pg.wait_for_timeout(500)
        body = await T('#app').inner_text()
        ok('Нов разход с падеж след 2 дни е в „Предстоящи плащания“', 'Разрешително' in body)
        await pg.click('.rem-actions .btn >> nth=0'); await pg.wait_for_timeout(500)
        ok('„Платено“ мести падежа с година', 'Следващо плащане' in await T('#toast').inner_text(), await T('#toast').inner_text())
        # --- Напомняне по км ---
        await pg.click('text=Напомняне'); await pg.wait_for_timeout(300)
        await pg.fill('.sheet input[placeholder="напр. Смяна на масло"]','Масло')
        await pg.fill('.sheet input[inputmode=numeric] >> nth=0','250500')
        await pg.click('.sheet >> text=Запази'); await pg.wait_for_timeout(400)
        ok('Напомняне по км е добавено', 'Масло' in await T('#app').inner_text())
        # --- Статистика + Excel ---
        await pg.goto(base+'/app#/stats'); await pg.wait_for_timeout(500)
        async with pg.expect_download() as dl:
            await pg.click('.hero-btn[aria-label="Свали в Excel"]')
        d = await dl.value; path = await d.path(); txt = open(path, encoding='utf-8-sig').read()
        ok('Excel файлът се сваля и съдържа смените', 'Дата;Начало' in txt and 'Чиста печалба' in txt, d.suggested_filename)
        for u in ['day','week','year','custom']:
            await pg.click(f'.seg-btn >> nth={["day","week","month","year","custom"].index(u)}'); await pg.wait_for_timeout(250)
        ok('Всички периоди в статистиката се отварят без грешка', not errs, errs[:2])
        # --- Профил ---
        await pg.goto(base+'/app#/car'); await pg.wait_for_timeout(300)
        ctxt = await T('#app').inner_text()
        ok('„Колата и ефирът“ е отделна страница с вид кола, гориво и ефир', all(x in ctxt for x in ['Колата е','Гориво','Ефир / диспечер']))
        await pg.click('.seg-btn:has-text("Седмица")'); await pg.click('.tile:has-text("Такса")'); await pg.keyboard.type('40'); await pg.click('text=Готово')
        await pg.click('.save-bar .btn'); await pg.wait_for_timeout(400)
        ok('При смяна на ефира пита от кога важи', 'От кога важи' in await T('.sheet').inner_text())
        await pg.click('.sheet .btn-primary'); await pg.wait_for_timeout(500)
        await pg.goto(base+'/app#/costs'); await pg.wait_for_timeout(300)
        ok('Смяна на ефира на 40 €/седм. от профила', '40 € на седмица' in await T('#app').inner_text())
        await pg.goto(base+'/app#/profile'); await pg.wait_for_timeout(300)
        txt = await T('#app').inner_text()
        ok('„Моят профил“ е само личното: данни, снимки, отчети, парола, помощ, изход', all(x in txt for x in ['Лични данни','Снимки','Отчет в PDF','Всички смени (Excel)','Смяна на паролата','Поверителност','Общи условия','Изход']) and 'Ефир / диспечер' not in txt)
        await pg.click('.seg-btn:has-text("Тъмна")'); await pg.wait_for_timeout(150)
        ok('Тъмна тема се включва', await pg.evaluate('document.documentElement.dataset.theme')=='dark')
        await pg.click('.seg-btn:has-text("Автоматично")')
        await pg.click('text=Смяна на паролата'); await pg.wait_for_timeout(250)
        await pg.fill('.sheet input >> nth=0','грешна'); await pg.fill('.sheet input >> nth=1','654321'); await pg.click('.sheet .btn-page'); await pg.wait_for_timeout(150)
        ok('Грешна текуща парола се отказва', 'Грешна' in await T('.sheet .err').inner_text())
        await pg.fill('.sheet input >> nth=0','123456'); await pg.click('.sheet .btn-page'); await pg.wait_for_timeout(400)
        await pg.click('text=Изход'); await pg.wait_for_timeout(300)
        await pg.fill('input[type=email]','test@test.bg'); await pg.fill('input[type=password]','123456'); await pg.click('button[type=submit]'); await pg.wait_for_timeout(300)
        ok('Старата парола вече не работи', 'Грешен' in await T('.err').inner_text())
        await pg.fill('input[type=password]','654321'); await pg.click('button[type=submit]'); await pg.wait_for_timeout(400)
        ok('Вход с новата парола', '#/home' in pg.url)
        # --- Ширина и грешки ---
        for route in ['home','shifts','stats','costs','profile','car','me','money','shift/new']:
            await pg.goto(base+'/app#/'+route); await pg.wait_for_timeout(350)
            w = await pg.evaluate('document.documentElement.scrollWidth')
            if w>390: ok(f'Без хоризонтално превъртане: {route}', False, w)
        ok('Без хоризонтално превъртане на всички страници (390 px)', not any('превъртане' in r and r.startswith('FAIL') for r in R))
        ok('Без грешки в конзолата', not errs, errs[:3])
        print('\n'.join(R)); print('FAILS:', sum(r.startswith('FAIL') for r in R), '/', len(R))
        await b.close()
try:
    asyncio.run(main())
except Exception as e:
    print('\n'.join(R)); print('CRASH:', str(e).split('\n')[0])
