# Пълен път: шофьор пише → админ отговаря → шофьор вижда; подреждане с влачене; роли; 2FA; промо; преглед като шофьор
import asyncio, re
from playwright.async_api import async_playwright

R=[]
def ok(n,c,x=''): R.append(f"{'PASS' if c else 'FAIL'}  {n}{'  ['+str(x)+']' if x!='' else ''}")
async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch(); ctx = await b.new_context(viewport={'width':1280,'height':2000}); await ctx.add_init_script("try{localStorage.setItem('profitaxi.paidMode','1')}catch(e){}")
        await ctx.add_init_script("try{localStorage.setItem('profitaxi.adminTour','done');sessionStorage.setItem('profitaxi.oneIntro','1')}catch(e){}")
        base='http://localhost:8765'; errs=[]
        d = await ctx.new_page(); d.on('pageerror', lambda e: errs.append('drv:'+str(e)))
        await d.goto(base+'/app'); await d.evaluate('localStorage.clear()'); await d.goto(base+'/app#/login'); await d.wait_for_timeout(500)
        await d.fill('input[type=email]','ivan@demo.bg'); await d.fill('input[type=password]','demo123'); await d.click('button[type=submit]'); await d.wait_for_timeout(700)
        await d.keyboard.press('Escape'); await d.goto(base+'/app#/help'); await d.wait_for_timeout(500)
        await d.fill('textarea', 'Тест въпрос от Иван'); await d.click('text=Изпрати >> nth=0'); await d.wait_for_timeout(400)
        ok('Шофьорът изпраща въпрос', 'Тест въпрос от Иван' in await d.inner_text('#app'))
        await d.goto(base+'/app#/home'); await d.wait_for_timeout(400)
        a = await ctx.new_page(); a.on('pageerror', lambda e: errs.append('adm:'+str(e)))
        await a.goto(base+'/admin.html'); await a.wait_for_timeout(400)
        await a.fill('input[type=email]','admin@profitaxi.bg'); await a.fill('input[type=password]','admin123'); await a.click('button[type=submit]'); await a.wait_for_timeout(800)
        await a.evaluate("location.hash='#/messages?t=inbox'"); await a.wait_for_timeout(500)
        await a.click('.tk-row:has-text("Тест въпрос")'); await a.wait_for_timeout(400)
        await a.fill('.bubble ~ * textarea, .card textarea', 'Отговор от админа'); await a.click('[data-zone="messages.reply"] >> text=Изпрати'); await a.wait_for_timeout(400)
        await d.goto(base+'/app#/home'); await d.wait_for_timeout(600)
        ok('Шофьорът вижда „Отговорихме ти“ на Днес', 'Отговорихме ти' in await d.inner_text('#app'))
        await d.goto(base+'/app#/help'); await d.wait_for_timeout(500)
        ok('Отговорът е в „Пиши ни“', 'Отговор от админа' in await d.inner_text('#app'))
        # Подреждане: влачим картата „Отчет за седмицата“ най-отгоре
        await a.evaluate("location.hash='#/overview'"); await a.wait_for_timeout(600)
        first = await a.eval_on_selector('[data-zone="overview"]', 'z=>z.children[0].dataset.k')
        await a.click('#adm-arrange'); await a.wait_for_timeout(300)
        src = await a.query_selector('[data-zone="overview"] > [data-k="attention"] .card-title')
        dst = await a.query_selector('[data-zone="overview"] > [data-k="happened"]')
        sb = await src.bounding_box(); db = await dst.bounding_box()
        await a.mouse.move(sb['x']+40, sb['y']+10); await a.mouse.down(); await a.mouse.move(sb['x']+60, sb['y']-30, steps=4)
        await a.mouse.move(db['x']+80, db['y']+10, steps=12); await a.mouse.up(); await a.wait_for_timeout(300)
        now = await a.eval_on_selector('[data-zone="overview"]', 'z=>z.children[0].dataset.k')
        ok('Влачене с мишката мести картата', now=='attention', f'{first} -> {now}')
        await a.click('.arr-bar >> text=Готово'); await a.reload(); await a.wait_for_timeout(800)
        ok('Подредбата се помни след презареждане', await a.eval_on_selector('[data-zone="overview"]', 'z=>z.children[0].dataset.k')=='attention')
        # Стрелки и скриване
        await a.click('#adm-arrange'); await a.wait_for_timeout(200)
        await a.click('[data-zone="overview"] > [data-k="alerts"]'); await a.click('.arr-bar [aria-label="Нагоре"]'); await a.wait_for_timeout(200)
        order = await a.eval_on_selector('[data-zone="overview"]', 'z=>[...z.children].map(c=>c.dataset.k)')
        ok('Стрелка нагоре мести избраното', order.index('alerts') < order.index('nums'), order[:4])
        await a.click('.arr-bar button:has-text("Скрий")'); await a.click('.arr-bar >> text=Готово'); await a.wait_for_timeout(300)
        ok('Скритата карта не се вижда', not await a.is_visible('[data-zone="overview"] > [data-k="alerts"]'))
        # бутоните също се местят
        await a.click('#adm-arrange'); await a.click('[data-zone="overview.weekly"] > [data-k="copy"]'); await a.click('.arr-bar [aria-label="Нагоре"]'); await a.click('.arr-bar >> text=Готово')
        ok('Бутоните също се подреждат', await a.eval_on_selector('[data-zone="overview.weekly"]', 'z=>z.children[0].dataset.k')=='copy')
        # менюто
        await a.click('#adm-arrange'); await a.click('[data-zone="nav"] > [data-k="money"]', modifiers=[]) ; await a.wait_for_timeout(300)
        ok('В режим „Подреди“ менюто води към страницата', '#/money' in a.url)
        await a.click('.arr-bar >> text=Както беше'); await a.wait_for_timeout(300); await a.click('.arr-bar >> text=Готово')
        # Търсене
        await a.fill('#adm-search', '0888 214'); await a.wait_for_timeout(300)
        ok('Търсене по телефон намира шофьора', 'Иван Петров' in await a.inner_text('.gs-res'))
        await a.fill('#adm-search', 'СВ4827'); await a.wait_for_timeout(300)
        ok('Търсене по номер на кола', 'Иван Петров' in await a.inner_text('.gs-res'))
        await a.fill('#adm-search', '')
        # Камбанка
        await a.click('#adm-bell'); await a.wait_for_timeout(200)
        ok('Камбанката показва известия', await a.locator('.bell-pop.open .alert-row').count() > 0)
        await a.keyboard.press('Escape'); await a.mouse.click(700, 500)
        # Промо код при регистрация
        await d.goto(base+'/app#/profile'); await d.wait_for_timeout(400); await d.click('text=Изход'); await d.wait_for_timeout(300)
        await d.goto(base+'/app#/register?promo=START2'); await d.wait_for_timeout(400)
        await d.fill('input[autocomplete=name]','Промо Тест'); await d.fill('input[type=email]','promo@test.bg'); await d.fill('input[type=password]','123456')
        await d.fill('input[type=tel]','0877555666'); await d.wait_for_timeout(100)
        await d.select_option('select >> nth=0','Сливен'); await d.wait_for_timeout(150); await d.select_option('select >> nth=1','Perfect Taxi')
        await d.click('text=Собствена'); await d.click('input[type=checkbox]'); await d.click('button[type=submit]'); await d.wait_for_timeout(500)
        days = await d.evaluate("(()=>{const db=JSON.parse(localStorage.getItem('profitaxi.v5'));const u=db.users.find(x=>x.email==='promo@test.bg');return [u.source,u.promo,Math.round((new Date(u.subscription.validUntil)-new Date(new Date().toISOString().slice(0,10)))/864e5)]})()")
        ok('Промо START2 дава +2 месеца и източник „промо“', days[0]=='promo' and days[1]=='START2' and days[2]>=70, days)
        # Защо спря
        await d.goto(base+'/app#/profile'); await d.wait_for_timeout(300)
        await d.evaluate("localStorage.removeItem('profitaxi.session')"); await d.goto(base+'/app#/login'); await d.wait_for_timeout(300)
        await d.fill('input[type=email]','stoyan@demo.bg'); await d.fill('input[type=password]','demo123'); await d.click('button[type=submit]'); await d.wait_for_timeout(500)
        await d.evaluate("(()=>{const db=JSON.parse(localStorage.getItem('profitaxi.v5'));const u=db.users.find(x=>x.email==='stoyan@demo.bg');db.churn=db.churn.filter(c=>c.userId!==u.id);localStorage.setItem('profitaxi.v5',JSON.stringify(db))})()"); await d.reload(); await d.wait_for_timeout(500)
        await d.click('.churn-opts >> text=Скъпо е'); await d.click('.churn >> text=Изпрати'); await d.wait_for_timeout(300)
        ok('Изтекъл шофьор отговаря „Защо спря“', 'Благодарим' in await d.inner_text('#app'))
        await a.evaluate("location.hash='#/growth?t=churn'"); await a.wait_for_timeout(500)
        ok('Отговорът е в „Растеж → Защо се отказват“', 'Стоян Ангелов' in await a.inner_text('main'))
        # Преглед като шофьор
        did = await a.evaluate("JSON.parse(localStorage.getItem('profitaxi.v5')).users.find(u=>u.email==='maria@demo.bg').id")
        pv = await ctx.new_page(); await pv.goto(base+f'/app?preview={did}#/home'); await pv.wait_for_timeout(800)
        ok('„Виж като шофьор“ показва приложението на Мария', 'Преглед като Мария' in await pv.inner_text('body'))
        # Роля поддръжка
        c2 = await b.new_context(viewport={'width':1280,'height':900}); await c2.add_init_script("try{localStorage.setItem('profitaxi.paidMode','1')}catch(e){}"); a2 = await c2.new_page()
        await a2.add_init_script("try{localStorage.setItem('profitaxi.adminTour','done')}catch(e){}")
        await a2.goto(base+'/admin.html'); await a2.wait_for_timeout(400)
        await a2.fill('input[type=email]','support@profitaxi.bg'); await a2.fill('input[type=password]','support123'); await a2.click('button[type=submit]'); await a2.wait_for_timeout(700)
        nav = await a2.eval_on_selector_all('.adm-nav a', 'e=>e.map(x=>x.innerText.split("\\n")[0])')
        ok('Поддръжка не вижда „Пари“', 'Пари' not in nav and 'Съобщения' in nav, nav)
        await a2.evaluate("location.hash='#/money'"); await a2.wait_for_timeout(300)
        ok('Поддръжка няма достъп до /money', '#/overview' in a2.url)
        await a2.click('text=Изход'); await a2.wait_for_timeout(300)
        await a2.fill('input[type=email]','one@partner.bg'); await a2.fill('input[type=password]','one123'); await a2.click('button[type=submit]'); await a2.wait_for_timeout(700)
        await a2.evaluate("location.hash='#/drivers'"); await a2.wait_for_timeout(500)
        rows = await a2.locator('.tbl tbody tr').all_inner_texts()
        ok('Партньор One вижда само своите шофьори', rows and all('ONE' in r for r in rows), len(rows))
        # 2FA
        await a.evaluate("location.hash='#/settings?t=security'"); await a.wait_for_timeout(400)
        await a.click('[aria-label="Двуфакторно влизане"]'); await a.wait_for_timeout(300)
        await a.click('text=Изход'); await a.wait_for_timeout(300)
        await a.fill('input[type=email]','admin@profitaxi.bg'); await a.fill('input[type=password]','admin123'); await a.click('button[type=submit]'); await a.wait_for_timeout(400)
        code = re.findall(r'\d{6}', await a.inner_text('#toast'))[-1]
        await a.fill('input[autocomplete=one-time-code]', '000000'); await a.click('button[type=submit]'); await a.wait_for_timeout(200)
        ok('Грешен код не пуска', 'Грешен код' in await a.inner_text('.err'))
        await a.fill('input[autocomplete=one-time-code]', code); await a.click('button[type=submit]'); await a.wait_for_timeout(600)
        ok('Двуфакторно влизане с код', await a.locator('.adm-nav').count()==1)
        await a.evaluate("location.hash='#/control?t=log'"); await a.wait_for_timeout(400)
        ok('Дневникът записва промяната на настройките', 'twoFactor' in await a.inner_text('main'))
        # --- окончателният пакет за админа ---
        await a.evaluate("location.hash='#/overview'"); await a.wait_for_timeout(600)
        ok('Днес е изчистена: картата, целта и отчетът са скрити', not await a.is_visible('[data-zone="overview"] > [data-k="map"]') and not await a.is_visible('[data-zone="overview"] > [data-k="weekly"]'))
        await a.evaluate("location.hash='#/stats?t=cities'"); await a.wait_for_timeout(600)
        ok('Картата е в Статистика → Градове', await a.is_visible('.map-card'))
        await a.evaluate("location.hash='#/money'"); await a.wait_for_timeout(500)
        ok('Целта и седмичният отчет са в Пари', 'Цел за бизнеса' in await a.inner_text('main') and 'Отчет за седмицата' in await a.inner_text('main'))
        await a.evaluate("location.hash='#/control'"); await a.wait_for_timeout(500)
        ok('Контрол → Сигнали е кратко обобщение по групи', await a.locator('.sig-grid .sig').count() >= 5)
        ok('Няма сигнал „Нов шофьор“', 'Нов шофьор' not in await a.inner_text('main'))
        await a.evaluate("location.hash='#/drivers'"); await a.wait_for_timeout(500)
        ok('Колоната е „Чисто за 30 дни“', 'Чисто за 30 дни' in await a.inner_text('thead'))
        did = await a.evaluate("JSON.parse(localStorage.getItem('profitaxi.v5')).users.find(u=>u.email==='ivan@demo.bg').id")
        await a.evaluate(f"location.hash='#/driver/{did}'"); await a.wait_for_timeout(600)
        ok('„Обади се“ и „Viber“ с +359', (await a.get_attribute('a:has-text("Обади се")', 'href')).startswith('tel:+359') and 'viber://chat?number=%2B359' in await a.get_attribute('a:has-text("Viber")', 'href'))
        today = await a.evaluate("(d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0'))(new Date())")
        await a.fill('textarea[placeholder*="Обади се"]', 'Обади се за фактурата'); await a.evaluate("(v)=>{const i=document.querySelector('input[aria-label=\"Напомни ми на\"]');i.value=v;i.dispatchEvent(new Event('input',{bubbles:true}));i.dispatchEvent(new Event('change',{bubbles:true}))}", today)
        await a.click('.note-add >> text=Добави'); await a.wait_for_timeout(400)
        await a.evaluate("location.hash='#/overview'"); await a.wait_for_timeout(500)
        ok('Бележка със срок излиза в „Изисква внимание“', 'Обади се за фактурата' in await a.inner_text('.attention'))
        await a.evaluate(f"location.hash='#/driver/{did}'"); await a.wait_for_timeout(500); await a.click('.note-row >> text=Свършено'); await a.wait_for_timeout(300)
        await a.evaluate("location.hash='#/overview'"); await a.wait_for_timeout(500)
        ok('След „Свършено“ напомнянето изчезва', 'Обади се за фактурата' not in await a.inner_text('.attention'))
        await a.evaluate("location.hash='#/messages?t=inbox'"); await a.wait_for_timeout(500)
        await a.click('.tk-row >> nth=0'); await a.wait_for_timeout(300); await a.click('.quick:has-text("Проверяваме")')
        ok('Готов отговор попълва текста', 'Проверяваме' in await a.eval_on_selector('.card textarea', 'e=>e.value'))
        await a.evaluate("location.hash='#/growth'"); await a.wait_for_timeout(500)
        ok('Растеж → Този месец срещу миналия', 'срещу' in await a.inner_text('main') and 'Нови регистрации' in await a.inner_text('main'))
        await a.evaluate("location.hash='#/dev'"); await a.wait_for_timeout(400)
        ok('Развитие: анкета и предложения са в „Мнения“', await a.locator('.adm-tabs a').count()==4)
        auto = await a.evaluate("JSON.parse(localStorage.getItem('profitaxi.v5')).messages.filter(m=>m.auto).length")
        ok('Автоматичните напомняния са изпратени', auto > 0, auto)
        # препоръка: месец безплатно само когато поканеният плати
        rid = await a.evaluate("""(()=>{const db=JSON.parse(localStorage.getItem('profitaxi.v5'));const iv=db.users.find(u=>u.email==='ivan@demo.bg');const x=db.users.find(u=>u.role==='driver'&&u.subscription.plan==='trial'&&!u.referredBy);x.referredBy=iv.id;x.subscription.paidSince=null;localStorage.setItem('profitaxi.v5',JSON.stringify(db));return [x.id, iv.subscription.validUntil]})()""")
        await a.reload(); await a.wait_for_timeout(500)
        await a.evaluate(f"location.hash='#/driver/{rid[0]}'"); await a.wait_for_timeout(500); await a.click('[data-zone="driver.sub"] >> text=+30 дни'); await a.wait_for_timeout(400)
        after = await a.evaluate("JSON.parse(localStorage.getItem('profitaxi.v5')).users.find(u=>u.email==='ivan@demo.bg').subscription.validUntil")
        ok('Когато поканеният плати, поканилият получава +30 дни', after > rid[1], f'{rid[1]} -> {after}')
        ok('Без грешки в JS', not errs, errs[:3])
        print('\n'.join(R)); print('FAILS', sum(r.startswith('FAIL') for r in R),'/',len(R))
        await b.close()
try: asyncio.run(main())
except Exception as e: print('\n'.join(R)); print('CRASH', str(e)[:300])
